### ISSUE TITLE
Mosaik dApp: Could not load app

### ISSUE THREAD

**Issue by 0xOdy** [ergoplatform/ergo-wallet-app#138]
Hello,

I am trying to try the mosaik dApp, but I am running into issue (See screenshot)
Am running the desktop ergo wallet app on Manjaro (Linux).

![image](https://user-images.githubusercontent.com/80256731/184180285-ba1efefa-366f-493d-91e5-f583085dc46e.png)

**Comment by MrStahlfelge** [comment]
Hey, which version are you running?
When you start the wallet from command line with --debug it will print out more information. Can you paste the output here?

Thank you!

**Comment by 0xOdy** [comment]
Hello,
I am running the version 2.0.2214 (Ergo Wallet desktop version)

Below the debug output
`2022-08-11 17:23:24.156 [StandaloneCoroutine] Refresh done, errors: true
Error: Error loading Mosaik app
NullPointerException Cannot read the array length because "<local2>" is null
java.lang.NullPointerException: Cannot read the array length because "<local2>" is null
	at com.google.gson.internal.bind.TypeAdapters$EnumTypeAdapter.<init>(TypeAdapters.java:779)
	at com.google.gson.internal.bind.TypeAdapters$30.create(TypeAdapters.java:818)
	at com.google.gson.Gson.getAdapter(Gson.java:458)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.createBoundField(ReflectiveTypeAdapterFactory.java:117)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.getBoundFields(ReflectiveTypeAdapterFactory.java:166)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.create(ReflectiveTypeAdapterFactory.java:102)
	at com.google.gson.Gson.getAdapter(Gson.java:458)
	at com.google.gson.Gson.toJson(Gson.java:696)
	at com.google.gson.Gson.toJsonTree(Gson.java:597)
	at com.google.gson.Gson.toJsonTree(Gson.java:576)
	at org.ergoplatform.mosaik.serialization.MosaikSerializer.contextHeadersMap(MosaikSerializer.java:61)
	at org.ergoplatform.mosaik.OkHttpBackendConnector.loadMosaikApp(OkHttpBackendConnector.kt:27)
	at org.ergoplatform.mosaik.MosaikRuntime$loadMosaikApp$1.invokeSuspend(MosaikRuntime.kt:237)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:39)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
`

**Comment by MrStahlfelge** [comment]
Thank you very much for reporting; the shrinker reducing the size of the packaged app was too aggressive and shrinked necessary information away. I will release a fixed version today.
